### ISSUE TITLE
Users stream throws `KeyError`

### ISSUE THREAD

**Issue by prratek** [Matatika/tap-auth0#2]
I'm running the tap with just `stream_auth0_users` selected and [this line](https://github.com/Matatika/tap-auth0/blob/master/tap_auth0/streams.py#L71) throws a `KeyError`. I added some logging and the result from `self.poll_job(...)` looks like this - it doesn't have a `location` key
```python
{'type': 'users_export', 'status': 'processing', 'format': 'json', 'fields': [{'name': 'user_id'}, {'name': 'email'}, {'name': 'email_verified'}, {'name': 'username'}, {'name': 'phone_number'}, {'name': 'phone_verified'}, {'name': 'created_at'}, {'name': 'updated_at'}, {'name': 'identities'}, {'name': 'app_metadata'}, {'name': 'user_metadata'}, {'name': 'picture'}, {'name': 'name'}, {'name': 'nickname'}, {'name': 'multifactor'}, {'name': 'last_ip'}, {'name': 'last_login'}, {'name': 'logins_count'}, {'name': 'blocked'}, {'name': 'given_name'}, {'name': 'family_name'}, {'name': 'last_password_reset'}, {'name': 'locale'}], 'percentage_done': 2, 'time_left_seconds': 162, 'created_at': '2022-03-21T22:42:48.637Z', 'id': 'job_CCBtbR1e1bp5yfcg'}
```

**Comment by ReubenFrankel** [comment]
@prratek Let me know if that fix works for you!

Looking at the logging data you provided, you're probably going to have to provide some overrides for the `job_poll_interval_ms` and `job_poll_max_count` settings, as I don't think the current defaults will be sufficient for you given that `time_left_seconds` is accurate.

I expect there is an enhancement that can be made to poll the job intelligently based on `time_left_seconds`. I'll have a look into that in the future.

**Comment by ReubenFrankel** [comment]
@prratek Let me know if that fix works for you!

Looking at the logging data you provided, you're probably going to have to provide some overrides for the `job_poll_interval_ms` and `job_poll_max_count settings`, as I don't think the current defaults will be sufficient for your use-case (if `time_left_seconds` is accurate).

I expect there is an enhancement that can be made to poll the job intelligently based on `time_left_seconds`. I'll have a look into that in the future. 😄

**Comment by ReubenFrankel** [comment]
@prratek Let me know if that fix works for you!

Looking at the logging data you provided, you're probably going to have to provide some overrides for the `job_poll_interval_ms` and `job_poll_max_count settings`, as I don't think the current defaults will be sufficient for your use-case (if `time_left_seconds` is accurate).

I expect there is an enhancement that can be made to poll the job intelligently based on `time_left_seconds`. I'll have a look into that in the future. 😄

**Comment by prratek** [comment]
Thanks for spotting the issue and pushing a fix so quickly! Along with the tweaks to `job_poll_interval_ms` and `job_poll_max_count` it's running smoothly now

**Comment by ReubenFrankel** [comment]
> I expect there is an enhancement that can be made to poll the job intelligently based on `time_left_seconds`. I'll have a look into that in the future. 😄

See #15
